### ISSUE TITLE
Failing tests on 32-bit platforms

### ISSUE THREAD

**Issue by satta** [NeowayLabs/wabbit#14]
The test suite fails on 32-bit architectures (at least i386 and armhf, see https://tests.reproducible-builds.org/debian/rb-pkg/unstable/i386/golang-github-neowaylabs-wabbit.html) with the following error message (example from i386, Go 1.7, wabbit checkout commit cfb5237):

```
=== RUN   TestBasicUsage
--- PASS: TestBasicUsage (0.00s)
=== RUN   TestPubSub
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x80c4b7c]

goroutine 27 [running]:
panic(0x8164660, 0x1852a008)
	/usr/lib/go-1.7/src/runtime/panic.go:500 +0x331
sync/atomic.AddUint64(0x185924dc, 0x1, 0x0, 0x7, 0x1005e98)
	/usr/lib/go-1.7/src/sync/atomic/asm_386.s:112 +0xc
github.com/NeowayLabs/wabbit/amqptest/server.(*Channel).Publish(0x185924c0, 0x817f0ef, 0x4, 0x8181817, 0x11, 0x1858e2a0, 0x4, 0x8, 0x0, 0x0, ...)
	/home/satta/golang-github-neowaylabs-wabbit-0.0~git20170406.0.cfb5237/obj-i686-linux-gnu/src/github.com/NeowayLabs/wabbit/amqptest/server/channel.go:94 +0x5d
github.com/NeowayLabs/wabbit/amqptest.(*Publisher).Publish(0x1858e290, 0x817f0ef, 0x4, 0x8181817, 0x11, 0x1858e2a0, 0x4, 0x8, 0x0, 0x0, ...)
	/home/satta/golang-github-neowaylabs-wabbit-0.0~git20170406.0.cfb5237/obj-i686-linux-gnu/src/github.com/NeowayLabs/wabbit/amqptest/publisher.go:28 +0x81
github.com/NeowayLabs/wabbit_test.pub(0x81f9660, 0x18594090, 0x1856c100, 0x185922c0)
	/home/satta/golang-github-neowaylabs-wabbit-0.0~git20170406.0.cfb5237/obj-i686-linux-gnu/src/github.com/NeowayLabs/wabbit/amqp_test.go:104 +0x54e
created by github.com/NeowayLabs/wabbit_test.TestPubSub
	/home/satta/golang-github-neowaylabs-wabbit-0.0~git20170406.0.cfb5237/obj-i686-linux-gnu/src/github.com/NeowayLabs/wabbit/amqp_test.go:293 +0x259
exit status 2
FAIL	github.com/NeowayLabs/wabbit	0.011s
?   	github.com/NeowayLabs/wabbit/amqp	[no test files]
=== RUN   TestDial
--- PASS: TestDial (0.00s)
=== RUN   TestAutoRedial
--- PASS: TestAutoRedial (10.00s)
=== RUN   TestConnMock
--- PASS: TestConnMock (0.00s)
PASS
ok  	github.com/NeowayLabs/wabbit/amqptest	10.012s
=== RUN   TestBasicConsumer
--- FAIL: TestBasicConsumer (0.00s)
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
	panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x80d2adc]

goroutine 35 [running]:
panic(0x816ac60, 0x1852a008)
	/usr/lib/go-1.7/src/runtime/panic.go:500 +0x331
testing.tRunner.func1(0x185a0100)
	/usr/lib/go-1.7/src/testing/testing.go:579 +0x14f
panic(0x816ac60, 0x1852a008)
	/usr/lib/go-1.7/src/runtime/panic.go:458 +0x40b
sync/atomic.AddUint64(0x1857229c, 0x1, 0x0, 0x818601f, 0x9)
	/usr/lib/go-1.7/src/sync/atomic/asm_386.s:112 +0xc
github.com/NeowayLabs/wabbit/amqptest/server.(*Channel).Publish(0x18572280, 0x8185606, 0x6, 0x8186930, 0xc, 0x1857a3f8, 0x5, 0x8, 0x0, 0x0, ...)
	/home/satta/golang-github-neowaylabs-wabbit-0.0~git20170406.0.cfb5237/obj-i686-linux-gnu/src/github.com/NeowayLabs/wabbit/amqptest/server/channel.go:94 +0x5d
github.com/NeowayLabs/wabbit/amqptest/server.TestBasicConsumer(0x185a0100)
	/home/satta/golang-github-neowaylabs-wabbit-0.0~git20170406.0.cfb5237/obj-i686-linux-gnu/src/github.com/NeowayLabs/wabbit/amqptest/server/channel_test.go:45 +0x94c
testing.tRunner(0x185a0100, 0x8199ca0)
	/usr/lib/go-1.7/src/testing/testing.go:610 +0x8c
created by testing.(*T).Run
	/usr/lib/go-1.7/src/testing/testing.go:646 +0x2a5
exit status 2
FAIL	github.com/NeowayLabs/wabbit/amqptest/server	0.015s
```

**Comment by satta** [comment]
Apparently this is an instance of https://github.com/golang/go/issues/6404 appearing. Indeed putting in a spacer `uint32` fixes the issue. See pull request.

**Comment by tiago4orion** [comment]
Thanks @satta for looking into that. Very strange bug by the way.
